name: mrobot_remote
description: "Remote controller for the mRobot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bonsoir: ^5.1.10
  logger: ^2.4.0
  loading_animation_widget: ^1.2.1
  web_socket_client: ^0.1.4
  video_player: ^2.9.1
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.6
  messagepack: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: assets/icons/app_icon.png

assets:
  - assets/icons/app_icon.png
