name: mrobot_remote
description: "Remote controller for the mRobot"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bonsoir: ^5.1.10
  logger: ^2.4.0
  loading_animation_widget: ^1.2.1
  web_socket_client: ^0.1.4
  cupertino_icons: ^1.0.6
  messagepack: ^0.2.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  video_player_media_kit: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/images/blank_frame.png
